name: Staging

on:
  push:
    branches:
      - staging-deployment-experiment

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: build_image
        id: build_image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: codebuddies/backend/cb-backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile
          workdir: project
          tag_names: true

      - name: start deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging
          transient: true
          desc: Setting up staging deployment for ${{ steps.build_image.outputs.tag }}

      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_STAGING_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          port: ${{ secrets.DO_STAGING_SSH_PORT }}
          username: ${{ secrets.DO_SSH_USER }}
          source: "project/docker-compose-staging.yaml"
          target: "./"

      - name: run deployment
        uses: appleboy/ssh-action@master
        env:
          DO_STAGING_DB_URL: ${{ secrets.DO_STAGING_DB_URL }}
          CB_IMAGE_TAG: ${{ steps.build_image.outputs.tag }}
          GITHUB_ACTOR: $GITHUB_ACTOR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DJANGO_SECRET_KEY: ${{ secrets.STAGING_DJANGO_SECRET_KEY }}
          DJANGO_ALLOWED_HOSTS: "${{ secrets.STAGING_ALLOWED_HOSTS }}"
        with:
          host: ${{ secrets.DO_STAGING_HOST }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          port: ${{ secrets.DO_STAGING_SSH_PORT }}
          username: ${{ secrets.DO_SSH_USER }}
          script_stop: true
          debug: true
          envs: DO_STAGING_DB_URL,CB_IMAGE_TAG,GITHUB_ACTOR,GITHUB_TOKEN,DJANGO_SECRET_KEY,DJANGO_ALLOWED_HOSTS
          script: |
            export DB_URL=$DO_STAGING_DB_URL
            export CB_IMAGE_TAG=$CB_IMAGE_TAG
            export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
            export DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
            docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
            docker-compose --project-name=-stage -f docker-compose-staging.yaml rm -f
            docker-compose --project-name=-stage -f docker-compose-staging.yaml pull
            docker-compose --project-name=-stage -f docker-compose-staging.yaml up -d
      - name: finish deployment
        uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: https://${{ secrets.DO_STAGING_HOST }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
